image: docker:stable

services:
  - docker:19.03.0-dind

variables:
  # SECRET_KEY: '2(o^nzfzonpqr*5d-6-trf1-l+s4zlvq-(v1u*f)acfb&h6$#!'  # Dummy secret key for CI pipeline
  # DJANGO_ALLOWED_HOSTS: 'localhost 127.0.0.1 [::1]'

stages:
  - build
  - test
  - deploy

Build and push stage:
  stage: build
  script:
    - docker login --username $CI_REGISTRY_USER --password "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA ./serina-project
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master
    - tests


Test stage:
  stage: test
  script:
    - docker login --username $CI_REGISTRY_USER --password "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # SECRET_KEY is a dummy key generated for this pipeline
    - docker run --rm -e SECRET_KEY='2(o^nzfzonpqr*5d-6-trf1-l+s4zlvq-(v1u*f)acfb&h6$#!' -e DJANGO_ALLOWED_HOSTS='localhost 127.0.0.1 [::1]' $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA py.test ./serina-project
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
    - tests


# Deploy stage:
#   stage: deploy
#   script:
#     - chmod 600 $DEPLOY_KEY_FILE
#     - ssh -i "$DEPLOY_KEY_FILE" -o "StrictHostKeyChecking=no" -o "IdentitiesOnly=yes" root@195.201.3.85:ICC-Epreuve 'docker-compose pull && docker-compose up -d'
#   only:
#     - master