image: docker:stable

services:
  - docker:19.03.0-dind



stages:
  - build
  - test
  - deploy

build docker image:
  stage: build
  only:
    - master
    - tests
  script:
    - env
    - docker login --username $CI_REGISTRY_USER --password "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - chmod +x ./serina-project/entrypoint*
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA ./serina-project
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA


test docker image:
  stage: test
  only:
    - master
    - tests
  variables: {
      SECRET_KEY: "mysupersecretkey",
      DJANGO_ALLOWED_HOSTS: "*"
  }

  script:
    - docker login --username $CI_REGISTRY_USER --password "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker run --rm $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA py.test ./serina-project
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
