version: '3.8'

services:
    web:
        container_name: serina_web
        build:
            context: ./serina-project
            dockerfile: Dockerfile.prod
        image: serina_django
        networks:
            - serina_network
        depends_on:
            - db
        restart: always
        expose:
            - 8000
        env_file:
            - .env.prod

        command: gunicorn serina.wsgi:application --bind 0.0.0.0:8000


    db:
        container_name: serina_db
        image: postgres:12.3
        networks:
            - serina_network
        volumes:
            - type: volume
              source: postgres_database_prod
              target: /var/lib/postgresql/data
        restart: always
        env_file:
            - .env.prod.db


    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        networks:
            - serina_network
        ports:
            - 1337:80
        depends_on:
            - web
        restart: always

volumes: 
    postgres_database_prod:


networks:
    serina_network:
