version: '3.8'

services:
    web:
        container_name: serina_web
        build:
            context: ./serina-project
            dockerfile: Dockerfile
        image: serina_django
        networks:
            - serina_network
        depends_on:
            - db
        volumes:
            - type: bind
              source: ./serina-project
              target: /usr/src/app
        restart: "no"
        ports:
            - 8000:8000
        env_file:
            - .env.dev

        command: bash scripts/runserver_plus.sh


    db:
        container_name: serina_db
        image: postgres:12.3-alpine
        networks:
            - serina_network
        volumes:
            - type: volume
              source: postgres_database_dev
              target: /var/lib/postgresql/data
        restart: unless-stopped

        environment:
            POSTGRES_DB: 'postgres_database_dev'
            POSTGRES_USER: 'postgres_user_dev'
            POSTGRES_PASSWORD: 'postgres_password_dev'


volumes: 
    postgres_database_dev:


networks:
    serina_network:
