version: '3.8'

services:
    dill:  # Django container
        container_name: serina-dill
        build:
            context: .
        image: django:3.0.8
        networks:
            - serina-network
        depends_on:
            - pumpkin
        volumes:
            - type: bind
              source: ./serina-project
              target: /src
        restart: "no"
        ports:
            - 8000:8000
        env_file:
            - .dev.env

        command: bash scripts/runserver.sh


    pumpkin:  # Postgres container
        container_name: serina-pumpkin
        image: postgres:12.3
        networks:
            - serina-network
        volumes:
            - type: volume
              source: pumpkin_database
              target: /var/lib/postgresql/data
        restart: unless-stopped

        environment:
            POSTGRES_DB: 'pumpkin'
            POSTGRES_USER: 'pumpkin'
            POSTGRES_PASSWORD: 'Pv16^6C&MzU#'


volumes: 
    pumpkin_database:


networks:
    serina-network:
