# Generated by Django 3.0.8 on 2020-08-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrating',
            old_name='student',
            new_name='created_by',
        ),
    ]
