# Generated by Django 3.0.8 on 2020-08-09 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200809_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='rate',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate'),
        ),
    ]
