# Generated by Django 3.1.1 on 2020-09-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200919_2142'),
        ('rating', '0004_auto_20200929_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrating',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='management.degree', verbose_name='Degree'),
        ),
    ]
