# Generated by Django 3.1.1 on 2020-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20200929_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='comment',
            field=models.TextField(max_length=512, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation date'),
        ),
    ]
