# Generated by Django 3.1.1 on 2020-10-04 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20200929_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='comment',
            field=models.TextField(help_text='Leave a comment you want to be displayed on your rate. Your comment will be shown as well as your rating on the home page and the module/degree page.', max_length=512, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update date'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='rate',
            field=models.PositiveIntegerField(help_text='Give a rate from 1 (very poor) to 5 (very good)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate'),
        ),
    ]
