# Generated by Django 3.0.8 on 2020-07-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('rank', models.PositiveIntegerField(unique=True, verbose_name='Rank')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Module level',
                'verbose_name_plural': 'Module levels',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('title', models.CharField(max_length=255, verbose_name='Module')),
                ('reference', models.CharField(max_length=5, verbose_name='Reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ECTS_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='ECTS value')),
                ('cost', models.FloatField(null=True, verbose_name='Cost')),
                ('charge_price', models.FloatField(null=True, verbose_name='Charge price')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('eligible_teachers', models.ManyToManyField(related_name='can_be_teached_by', to=settings.AUTH_USER_MODEL, verbose_name='Eligible teachers')),
                ('is_a_prerequisite_for', models.ManyToManyField(related_name='_module_is_a_prerequisite_for_+', to='management.Module', verbose_name='Is a prerequisite for (Modules)')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='management.ModuleLevel', verbose_name='Difficultiy level')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ('title', 'reference'),
            },
        ),
    ]
