# Generated by Django 3.0.8 on 2020-08-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='charge_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Charge price'),
        ),
        migrations.AlterField(
            model_name='module',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Cost'),
        ),
    ]
