# Generated by Django 3.0.8 on 2020-07-25 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='eligible_teachers',
            field=models.ManyToManyField(blank=True, related_name='can_be_teached_by', to=settings.AUTH_USER_MODEL, verbose_name='Eligible teachers'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_a_prerequisite_for',
            field=models.ManyToManyField(blank=True, related_name='_module_is_a_prerequisite_for_+', to='management.Module', verbose_name='Is a prerequisite for (Modules)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='reference',
            field=models.CharField(blank=True, max_length=7, verbose_name='Reference'),
        ),
    ]
