# Generated by Django 3.0.8 on 2020-08-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200802_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='reference',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Reference'),
        ),
    ]
