# Generated by Django 3.0.8 on 2020-07-24 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_auto_20200724_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ('-date_updated', '-date_created', 'title'), 'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curricula'},
        ),
        migrations.AlterModelOptions(
            name='modulelevel',
            options={'ordering': ('rank', '-date_updated', '-date_created'), 'verbose_name': 'Module level', 'verbose_name_plural': 'Module levels'},
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(related_name='modules_teached_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Modules teached as a teacher'),
        ),
    ]
