# Generated by Django 3.0.8 on 2020-07-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200725_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='modules',
            field=models.ManyToManyField(related_name='degrees', to='management.Module', verbose_name='Modules'),
        ),
    ]
