# Generated by Django 3.0.8 on 2020-07-26 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_auto_20200726_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('label', models.CharField(max_length=7, unique=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Maximum capacity')),
                ('recommended_capacity', models.PositiveIntegerField(verbose_name='Recommended capacity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_declared_by', to=settings.AUTH_USER_MODEL, verbose_name='Declared by')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('reference', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Reference')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='management.Module', verbose_name='Modules')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='management.Classroom', verbose_name='Classroom')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teached_by', to=settings.AUTH_USER_MODEL, verbose_name='Teached by')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('date_start', 'reference'),
            },
        ),
    ]
