# Generated by Django 3.0.8 on 2020-08-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200811_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='degreecategory',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='module',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='modulelevel',
            name='picture',
        ),
    ]
