# Generated by Django 3.0.8 on 2020-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200811_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='picture',
            field=models.ImageField(blank=True, default='management/rooms/', max_length=225, null=True, upload_to='management/default.jpg', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='management/courses/', max_length=225, null=True, upload_to='management/default.jpg', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='degree',
            name='picture',
            field=models.ImageField(blank=True, default='management/degrees/', max_length=225, null=True, upload_to='management/default.jpg', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='module',
            name='picture',
            field=models.ImageField(blank=True, default='management/modules/', max_length=225, null=True, upload_to='management/default.jpg', verbose_name='Picture'),
        ),
    ]
