# Generated by Django 3.0.8 on 2020-07-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_classroom_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nb_registrants',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount of registrants'),
        ),
    ]
