# Generated by Django 3.0.8 on 2020-07-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0006_course_nb_registrants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_a_prerequisite_for',
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='_module_prerequisite_+', to='management.Module', verbose_name='Is a prerequisite for (Modules)'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_room', to=settings.AUTH_USER_MODEL, verbose_name='Declared by'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches', to=settings.AUTH_USER_MODEL, verbose_name='Teached by'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='management.DegreeCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_degrees', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='degreecategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_degree_categories', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='module',
            name='eligible_teachers',
            field=models.ManyToManyField(blank=True, related_name='teachable_modules', to=settings.AUTH_USER_MODEL, verbose_name='Eligible teachers'),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='management.ModuleLevel', verbose_name='Difficultiy level'),
        ),
        migrations.AlterField(
            model_name='modulelevel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_module_levels', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
