# Generated by Django 3.0.8 on 2020-07-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200726_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='_module_prerequisites_+', to='management.Module', verbose_name='Is a prerequisite for (Modules)'),
        ),
    ]
