# Generated by Django 3.0.8 on 2020-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200726_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='postrequisites', to='management.Module', verbose_name='Prerequisites'),
        ),
    ]
