# Generated by Django 3.0.8 on 2020-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200813_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='picture',
            field=models.ImageField(blank=True, default='management/undraw_Books_l33t.png', max_length=225, null=True, upload_to='management/rooms/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, default='management/undraw_Books_l33t.png', max_length=225, null=True, upload_to='management/courses/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='picture',
            field=models.ImageField(blank=True, default='management/undraw_Books_l33t.png', max_length=225, null=True, upload_to='management/degrees/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='module',
            name='picture',
            field=models.ImageField(blank=True, default='management/undraw_Books_l33t.png', max_length=225, null=True, upload_to='management/modules/', verbose_name='Picture'),
        ),
    ]
