# Generated by Django 3.0.8 on 2020-08-23 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200813_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(default=datetime.date(2020, 8, 23), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 8, 24), verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
