# Generated by Django 3.1.1 on 2020-09-19 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0012_auto_20200918_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='nb_registrants',
        ),
        migrations.AddField(
            model_name='course',
            name='prebooked_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats unbookable by the regular students. Used for V.I.P. and substracted by the total amount of available seats.', verbose_name='Prebooked seats'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_end',
            field=models.DateField(help_text='When the course ends.', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date_start',
            field=models.DateField(help_text='When the course starts.', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='module',
            field=models.ForeignKey(help_text='Module teached in the created course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='management.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(help_text='Module teached in the created course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
