# Generated by Django 3.1.1 on 2020-10-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200919_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='All the modules which are part of the degree.', null=True, related_name='degrees', to='management.Module', verbose_name='Modules'),
        ),
    ]
