# Generated by Django 3.0.8 on 2020-07-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(verbose_name='Birthday date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postalCode',
            field=models.CharField(max_length=50, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postalLocality',
            field=models.CharField(max_length=50, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
