# Generated by Django 3.0.8 on 2020-08-03 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200802_2043'),
        ('registration', '0002_auto_20200803_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_registrations', to='management.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='student_rr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_rrs', to='registration.StudentRegistrationReport', verbose_name='Student Registration Report'),
        ),
    ]
