# Generated by Django 3.0.8 on 2020-08-03 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200804_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='student_final_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)], verbose_name='Final score'),
        ),
    ]
