# Generated by Django 3.0.8 on 2020-08-09 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Final score'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('APPROVED', 'Approved'), ('PAYED', 'Payed'), ('COMPLETED', 'Completed'), ('EXEMPTED', 'Exempted')], default='PENDING', max_length=9, verbose_name='Status'),
        ),
    ]
