# Generated by Django 3.0.8 on 2020-08-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200809_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleregistrationreport',
            name='date_payed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
    ]
