# Generated by Django 3.0.8 on 2020-08-03 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200804_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='student_final_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Final score'),
        ),
    ]
