# Generated by Django 3.0.8 on 2020-08-23 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20200823_0248'),
        ('registration', '0005_moduleregistrationreport_date_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_rrs', to='management.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='date_end',
            field=models.DateField(default=datetime.date(2020, 8, 25), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 8, 23), verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
