# Generated by Django 3.0.8 on 2020-08-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200804_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleregistrationreport',
            old_name='student_final_score',
            new_name='final_score',
        ),
    ]
