# Generated by Django 3.0.8 on 2020-08-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200805_0012'),
        ('registration', '0006_auto_20200804_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeregistrationreport',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='degreeregistrationreport',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules_rrs', to='management.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_rrs', to='management.Module', verbose_name='Registration module'),
        ),
    ]
