# Generated by Django 3.1.1 on 2020-09-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_moduleregistrationreport_exemption_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleregistrationreport',
            name='exemption_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Exemption reports'),
        ),
    ]
