# Generated by Django 3.1.1 on 2020-09-25 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200923_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeregistrationreport',
            name='exemption_report',
            field=models.FileField(blank=True, help_text='Send the documents that can provide you a exemption for this module. The documents will be verified by our staff and help them taking a decision regarding your request.', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Exemption reports'),
        ),
        migrations.AddField(
            model_name='degreeregistrationreport',
            name='exemption_request',
            field=models.BooleanField(default=False, help_text='If you already succeeded this or a similar module in another school or educational organization, you can ask for an exemption. This will prevent you from passing paying this module if your request is accepted by our staff.', verbose_name='Student exemption request'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='exemption_report',
            field=models.FileField(blank=True, help_text='Send the documents that can provide you a exemption for this module. The documents will be verified by our staff and help them taking a decision regarding your request.', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Exemption reports'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='annex_403',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Annex 403'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='archievement_certificates',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Modules archievement certificates'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='belgian_studies_history',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Belgian Studies History'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='exemption_report',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Exemption reports'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='id_picture',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], verbose_name='ID picture'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='job_organization_certificates',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Job organizations certificates'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='national_register_extract',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='National Register Extract'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='other_school_inscription_certificate',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Other schools inscription certificate'),
        ),
        migrations.AlterField(
            model_name='studentregistrationreport',
            name='secondary_education_certificate',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'jpeg', 'jpg', 'png'])], verbose_name='Secondary Education Certificate'),
        ),
    ]
