# Generated by Django 3.1.1 on 2020-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200929_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeregistrationreport',
            name='payed_fees',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Payed fees'),
        ),
        migrations.AddField(
            model_name='moduleregistrationreport',
            name='payed_fees',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Payed fees'),
        ),
    ]
