# Generated by Django 3.1.1 on 2020-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20201004_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='payed_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Payed fees'),
        ),
    ]
