# Generated by Django 3.1.1 on 2020-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20201004_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeregistrationreport',
            name='invoice_id',
            field=models.CharField(max_length=16, null=True, verbose_name='Invoice ID'),
        ),
        migrations.AddField(
            model_name='moduleregistrationreport',
            name='invoice_id',
            field=models.CharField(max_length=16, null=True, verbose_name='Invoice ID'),
        ),
    ]
