# Generated by Django 3.1.1 on 2020-10-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20201004_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeregistrationreport',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='Invoice ID'),
        ),
    ]
