# Generated by Django 3.1.1 on 2020-10-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20201004_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeregistrationreport',
            name='payed_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Payed fees'),
        ),
    ]
