# Generated by Django 3.1.1 on 2020-10-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201010_0407'),
        ('registration', '0016_auto_20201005_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeregistrationreport',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_registrations', to='management.degree', verbose_name='Registration degree'),
        ),
        migrations.AlterField(
            model_name='moduleregistrationreport',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_rrs', to='management.module', verbose_name='Registration module'),
        ),
    ]
